### ISSUE TITLE
Is there any way to update the value of $device.isTablet before filtering the code based on device? I am facing some issue with iPad ios 13+ Safari. It is being detected as Desktop but with the help of 'user-agent' we can handle it and force it to Tablet mode

### ISSUE THREAD

**Issue by sunilrana123** [nuxt-community/device-module#23] opened 2019-11-08 06:19 UTC

**Comment by lecoueyl** [comment] 2020-02-24 04:37
Duplicate of https://github.com/nuxt-community/device-module/issues/20

**Closed** 2021-01-27 09:47 UTC
